trigger:
- main

pool:
  vmImage: ubuntu-latest

pr:
 branches: 
   include:
     - main
     - prtest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo task name
    echo display name
  displayName: 'Run a multi-line script'
